export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS"
export const ALL_POST_REQUEST = "ALL_POST_REQUEST"
export const ALL_POST_FAIL = "ALL_POST_FAIL"

export const VISITED_POST_SUCCESS = "VISITED_POST_SUCCESS"
export const VISITED_POST_REQUEST = "VISITED_POST_REQUEST"
export const VISITED_POST_FAIL = "VISITED_POST_FAIL"


export const CLEAR_ERROR = "CLEAR_ERROR"