export const CLEAR_ERROR = "CLEAR_ERROR"


export const SHOP_CREATE_REQUEST = "SHOP_CREATE_REQUEST"
export const SHOP_CREATE_SUCCESS = "SHOP_CREATE_SUCCESS"
export const SHOP_CREATE_FAIL = "SHOP_CREATE_FAIL"


export const LOAD_SHOP_REQUEST = "LOAD_SHOP_REQUEST"
export const LOAD_SHOP_SUCCESS = "LOAD_SHOP_SUCCESS"
export const LOAD_SHOP_FAIL= "LOAD_SHOP_FAIL"